### ISSUE TITLE
Acrescentar nova verificação na validação da resposta do validador do CNJ

### ISSUE THREAD

**Issue by wilercoelho** [felipegiotto/justica_em_numeros_2016#15]
Código não pegou o erro do validador abaixo. Como sugestão verificar o jsonelement "qtdErros" e também o jsonarray "erros".

         ],
         "millisInsercao":1600088935235,
         "idElastic":"TRT7_1125_G1_50317_00102450520135070009",
         "dpj_identificadorProcesso":"TRT7_1125_G1_00102450520135070009",
         "dpj_numero":"00102450520135070009",
         "dpj_dataAjuizamento":"2013-04-23T14:18:37.000Z",
         "dpj_totalDatasMovimentosInvalidas":0,
         "dpj_orgaoJulgadorValido":true,
         "dpj_nomeClasseProcessual":"Ação Trabalhista - Rito Sumaríssimo",
         "dpj_classeProcessual":1125,
         "dpj_classeProcessualValida":true,
         "dpj_totalAssuntos":1,
         "dpj_totalAssuntosInvalidos":0,
         "dpj_assuntosInvalidos":[
            
         ],
         "dpj_totalMovimentos":53,
         "dpj_totalMovimentosInvalidos":0,
         "dpj_movimentosInvalidos":[
            
         ],
         "siglaTribunal":"TRT7",
         "grau":"G1"
      }
   ],
   "erros":{
      "00102450520135070009":[
         {
            "id":"ERRO_NUMERO_PROCESSO",
            "descricao":"Número de processo 00102450520135070009 INVÁLIDO! O número CORRIGIDO é: 0010245-72.2013.5.07.0009"
         }
      ]
   },
   "qtdErros":1,
   "qtdAcertos":0,
   "qtdTotal":1
}

**Comment by wilercoelho** [comment]
Outro exemplo de erro não capturado:

         "dpj_totalMovimentos":2,
         "dpj_totalMovimentosInvalidos":0,
         "dpj_movimentosInvalidos":[
            
         ],
         "siglaTribunal":"TRT7",
         "grau":"G2"
      }
   ],
   "erros":{
      "00360009219995070008":[
         {
            "id":"ERRO_ORGAO_JULGADOR_INVALIDO",
            "descricao":"O código do órgão julgador 82147 não existe na base de dados do CNJ. | Processo número 00360009219995070008"
         }
      ]
   },
   "qtdErros":1,
   "qtdAcertos":0,
   "qtdTotal":1
}

**Comment by ilfn** [comment]
Implementação incluída no PR https://github.com/felipegiotto/justica_em_numeros_2016/pull/34
